### ISSUE TITLE
Problem med curl installation via make install

### ISSUE THREAD

**Issue by annabatra** [dbwebb-se/oophp#14]
Får problem vid installationen av make install, när det kommer till shellshock / curl. Windows/cygwin
![curl](https://user-images.githubusercontent.com/45626337/78471393-4e5c5c00-7731-11ea-91f4-02c9ec33bdc4.png)

**Comment by mosbth** [comment]
Delvis beror det på att shellchek inte "går" att installera på Windows/Cygwin.

Gör så här för att undvika problemet.

1. Gå in i din `Makefile` och kommentera bort raden som installerar valideringsverktyget shellcheck. Lägg en `#` i början av raden. Det är denna raden som är den aktuella raden:
https://github.com/dbwebb-se/oophp/blob/master/example/redovisa/Makefile#L365

Jag skall uppdatera Makefilen så att problemet försvinner.

**Comment by mosbth** [comment]
Löst i samband med #15. Skall med senaste versionen av `example/redovisa/makefile` ej installera shellcheck på Cygwin.
