### ISSUE TITLE
Problem med shellcheck vid make check

### ISSUE THREAD

**Issue by bjorn-87** [dbwebb-se/oophp#15]
Får följande felmeddelande när jag kör make check 
```
--->   Check versions of Bash tools.
/bin/sh: .bin/shellcheck: det går inte att köra binär fil: Exec format error
shellcheck                 /cygdrive/c/Users/bjorn/dbwebb-kurser/oophp/me/redovisa/.bin/shellcheck
bats            Bats 0.4.0 /cygdrive/c/Users/bjorn/dbwebb-kurser/oophp/me/redovisa/.bin/bats

```
Os: Windows 10

**Comment by mosbth** [comment]
För tillfället så är det inget bekymmer att det ser ut så. Felet beror på att den versionen av shellcheck som installerats enbart fungerar på Linux.

Jag skall uppdatera Makefilen så att problemet försvinner.

Om ditt bekymmer enbart framträder när du kör `make check` så går det bra att ignorera det.

**Comment by mosbth** [comment]
Jag uppdaterade makefilen så att shellcheck inte installeras på Cygwin och att det installeras olika binärer på Linux och Darwin (MacOS).

Kommandot `make check` är en hjälp till felsökning och det kan vara okey att vissa kommandon inte fungerar/visas när man kör det.
