### ISSUE TITLE
Fel vid körande av make doc: "PHP Deprecated"

### ISSUE THREAD

**Issue by karlmartinsson** [dbwebb-se/oophp#18]
För följande felmeddelande väldigt många gånger i följd när jag kör make doc. Den dokumentation som genereras består också av samma felmeddelande upprepat väldigt många gånger. Har sett i chatten att flera andra har samma problem. Sitter på PHP 7.4.4 i terminalen. 

`PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in phar:///Users/karlmartinsson/dbwebb-kurser/oophp/me/redovisa/.bin/phpdoc/vendor/twig/twig/lib/Twig/Template.php on line 527`

**Comment by mosbth** [comment]
Jag får inte exakt samma felmeddelande som du, men i issuen #20 visar andra inlägget hur jag väljer att installera allra senaste versionen av phpdoc och det gör att mina felmeddelanden försvinner. 

Vill du pröva den varianten och se om det blir bättre?

Typ så här.

```
# Gå till kursreport
dbwebb update
cp example/redovisa/Makefile me/redovisa
cd me/redovisa
make install doc
```

**Comment by karlmartinsson** [comment]
Följde instruktionerna och så löste sig problemen. Toppen!
