### ISSUE TITLE
Avslutningsvideo till kursen

### ISSUE THREAD

**Issue by mipodi** [dbwebb-se/oophp#30]
Jag saknar en avslutningsvideo som ett closure för kursen. Streamlistan tar bara slut och det är lätt att det blir ett mentalt void hos kursdeltagaren.

![Screenshot 2020-05-15 at 15 53 38](https://user-images.githubusercontent.com/43996895/82057866-4397ce00-96c4-11ea-9897-c662c07f5dda.png)

**Comment by mosbth** [comment]
Det är säkert läraren som smiter undan och tror att alla studenter är nog nöjda...

Vi får helt enkelt starta upp OBS en sista gång innan sommaren :-)

**Comment by mipodi** [comment]
Hehe, okej, tack så mycket!

**Comment by mipodi** [comment]
Tack, såg videon nu! Trevlig sommar! Hurra hurra hurraaa!
